version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      special-pgadmin4-network:
        ipv4_address: 172.30.0.2

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      special-pgadmin4-network:
        ipv4_address: 172.30.0.4

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      special-pgadmin4-network:
        ipv4_address: 172.30.0.3
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: mydatabase
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/home/udev-2/special-pgadmin4/backend  # Mount backend folder into Nginx container
    networks:
      special-pgadmin4-network:
        ipv4_address: 172.30.0.5
    depends_on:
      - backend

networks:
  special-pgadmin4-network:
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/16"

volumes:
  postgres_data:
  pgadmin_data:
